Repository APP-Android2/FinalProject-ShoppingMallService-team6, pull requests merged in 2024-04, with the labels that each got.

#16 [feat]#13_작가 등록 화면 및 갱신 화면 구현
  .gradle/8.2/executionHistory/executionHistory.bin
  .gradle/8.2/executionHistory/executionHistory.lock
  .gradle/8.2/fileHashes/fileHashes.bin
  .gradle/8.2/fileHashes/fileHashes.lock
  .gradle/8.2/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/author/AddAythorActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/GuideLineFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/RegisterAuthorFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/UpdateAuthorActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/res/drawable/album_24fx.xml
  app/src/main/res/drawable/mygallery_cion.xml
  app/src/main/res/layout/activity_add_aythor.xml
  app/src/main/res/layout/activity_update_author.xml
  app/src/main/res/layout/fragment_guide_line.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_register_author.xml
Labels: UI

#18 [#10] 회원 정보 액티비티 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/UserInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ModifyUserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/UserInfoFragment.kt
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/fragment_modify_user_info.xml
  app/src/main/res/layout/fragment_user_info.xml
Labels: UI

#21 [#11] 구매한 작품 상세보기 activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchaseCancelFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/RefundFragment.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/res/layout/activity_purchased_piece_detail.xml
  app/src/main/res/layout/fragment_purchase_cancel.xml
  app/src/main/res/layout/fragment_purchased_piece_detail.xml
  app/src/main/res/layout/fragment_refund.xml
Labels: 기능, UI

#22 19 feature 하나의 정보들을 보여주는 activity 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/author/UpdateAuthorActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoOneActivity.kt
  app/src/main/res/layout/activity_info_one.xml
  app/src/main/res/values/themes.xml
Labels: 기능, UI

#26 [#23] 전체 정보를 보여주는 activity 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/author/UpdateAuthorActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllActivity.kt
  app/src/main/res/layout/activity_info_all.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/info_all.xml
Labels: 기능, UI

#28 [#24] 전시실 방문 activity 생성 및 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ApplyVisitGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
  app/src/main/res/drawable/minus_icon.xml
  app/src/main/res/layout/activity_visit_gallery.xml
  app/src/main/res/layout/fragment_apply_visit_gallery.xml
  app/src/main/res/layout/fragment_visit_gallery_history.xml
  app/src/main/res/layout/row_visit_gallery_history.xml
Labels: UI

#30 [#25] feature 작품 판매 신청 activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/java/kr/co/lion/unipiece/util/ToolUtil.kt
  app/src/main/res/drawable/arrowdropdown_icon.xml
  app/src/main/res/drawable/arrowdropup_icon.xml
  app/src/main/res/layout/activity_sales_application.xml
  app/src/main/res/layout/category_dialog.xml
  app/src/main/res/layout/fragment_login.xml
Labels: 기능, UI

#33 [#27] homefragment 구현
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/BannerVPAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/GalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/NewsFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/PromoteFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoOneActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
  app/src/main/res/drawable/logo_toolbar.png
  app/src/main/res/drawable/logo_toolbar_.png
  app/src/main/res/drawable/logo_toolbar_2.png
  app/src/main/res/layout/author_list.xml
  app/src/main/res/layout/fragment_gallery.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_news.xml
  app/src/main/res/layout/fragment_promote.xml
Labels: 기능, UI

#35 31 feature 작가 상세보기 액티비티 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorReviewBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/ModifyAuthorInfoFragment.kt
  app/src/main/res/drawable/close_icon.xml
  app/src/main/res/layout/activity_author_info.xml
  app/src/main/res/layout/fragment_author_info.xml
  app/src/main/res/layout/fragment_author_review_bottom_sheet.xml
  app/src/main/res/layout/fragment_modify_author_info.xml
  app/src/main/res/layout/row_author_review_bottom_sheet.xml
Labels: UI

#41 [#40] homefragment의 버튼 안보임 해결 작가 보여주기 divider 제거
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 버그, UI

#42 [#36] 회원정보 UI 관련 기능
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/UserInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ModifyUserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/UserInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/UserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/res/layout/activity_user_info.xml
  app/src/main/res/layout/fragment_modify_user_info.xml
  app/src/main/res/layout/fragment_user_info.xml
Labels: 기능

#45 [#38] BuyFragment 작품 리스트 추가
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyNewFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyPopFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyNewAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyPopAdapter.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_buy.xml
  app/src/main/res/layout/fragment_buy_new.xml
  app/src/main/res/layout/fragment_buy_pop.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_buy.xml
Labels: 기능, UI

#48 [#47] material3 관련 Theme 추가
  app/src/main/res/values/themes.xml
Labels: 기능

#51 [#43] 전시실 방문 UI 관련 기능
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ApplyVisitGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/res/layout/fragment_visit_gallery_history.xml
Labels: 기능

#37 [#34] 안드로이드 뒤로가기 버튼 버그 및 bottom navi 색깔 선택 버그 해결
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
Labels: 버그

#53 [Fix] #49 Recyclerview Adapter 분리
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllAdapter.kt
Labels: 리팩토링

#55 [#32} feature 나의 갤러리 fragment
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/InterestingPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/MyGalleryViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalePieceFragment.kt
  app/src/main/res/layout/fragment_interesting_piece.xml
  app/src/main/res/layout/fragment_my_gallery.xml
  app/src/main/res/layout/fragment_purchased_piece.xml
  app/src/main/res/layout/fragment_sale_piece.xml
  app/src/main/res/layout/row_interesting_piece.xml
  app/src/main/res/layout/row_purchased_piece.xml
  app/src/main/res/layout/row_sale_piece.xml
Labels: 기능, UI

#58 [#54] CustomDialog 생성
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/unipiece/util/CustomDialog.kt
  app/src/main/res/drawable/dialog_border.xml
  app/src/main/res/layout/dialog_custom.xml
  app/src/main/res/layout/fragment_login.xml
Labels: 기능, UI

#60 [#59] 작품 상세 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyNewFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyPopFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/SquareImageView.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/res/drawable/buy_detail_radius.xml
  app/src/main/res/drawable/test_piece_img.png
  app/src/main/res/layout/activity_buy_detail.xml
Labels: 기능, UI

#64 [#63] recyclerview 클릭 이벤트 구현
  app/src/main/java/kr/co/lion/unipiece/ui/home/GalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/NewsFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/PromoteFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllAdapter.kt
Labels: 기능, 리팩토링

#62 [#52] 작가 상세 보기 UI 관련 기능
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorReviewBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/ModifyAuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/res/layout/row_author_pieces.xml
Labels: 기능

#66 [#56] fix 테마 호환성 버그
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchaseCancelFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/RefundFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/res/layout/activity_sales_application.xml
  app/src/main/res/layout/category_dialog.xml
  app/src/main/res/layout/fragment_purchase_cancel.xml
  app/src/main/res/layout/fragment_purchased_piece_detail.xml
  app/src/main/res/layout/fragment_refund.xml
  app/src/main/res/values/themes.xml
Labels: 버그, UI

#70 [#65] homefragment의 작가 recyclerview 수정
  app/src/main/java/kr/co/lion/unipiece/ui/home/AuthorAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
Labels: 기능, 리팩토링

#74 [#68] feature 나의 갤러리
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/InterestingPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchaseCancelFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/RefundFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalePieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/InterestingPieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/MyGalleryViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/PurchasedPieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/SalePieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/util/KeyBoardUtil.kt
  app/src/main/res/layout/fragment_purchase_cancel.xml
  app/src/main/res/layout/fragment_purchased_piece_detail.xml
  app/src/main/res/layout/fragment_refund.xml
Labels: 기능, 리팩토링, UI

#78 [#75] feature 주문하기 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/payment/cart/CartActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderMainFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderSuccessFragment.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/activity_order.xml
  app/src/main/res/layout/fragment_order_main.xml
  app/src/main/res/layout/fragment_order_success.xml
  app/src/main/res/layout/row_cart.xml
  app/src/main/res/layout/row_order_main.xml
Labels: 기능, UI

#80 [#77] 뒤로가기 오류들 해결
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyNewFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyPopFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/adapter/RankAuthorVPAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/SearchFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/SearchResultFragment.kt
Labels: 버그

#82 [#81] 홈화면과 검색화면 연결 완료
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/res/layout/fragment_home.xml
Labels: 기능, UI

#84 [Feat] mutli viewholder로 검색결과 recylcerview 수정
  app/src/main/java/kr/co/lion/unipiece/ui/search/SearchResultFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchAuthorAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchAuthorData.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchAuthorViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchPieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchPieceData.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchPieceViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchResultAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchResultData.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchResultViewType.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/TitleAuthorViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/TitlePieceViewHolder.kt
  app/src/main/res/layout/fragment_search_result.xml
  app/src/main/res/layout/title_search_author.xml
  app/src/main/res/layout/title_search_piece.xml
Labels: 기능, 리팩토링, UI

#85 [Feature] #79 배송지 관리 화면 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/CustomFullDialogListener.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/CustomFullDialogMaker.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/DeliveryActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/DeliveryAddFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/DeliveryManagerFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderMainFragment.kt
  app/src/main/java/kr/co/lion/unipiece/util/FragmentUtil.kt
  app/src/main/res/layout/activity_delivery.xml
  app/src/main/res/layout/dialog_delivery_add.xml
  app/src/main/res/layout/fragment_delivery_add.xml
  app/src/main/res/layout/fragment_delivery_manager.xml
  app/src/main/res/layout/row_delivery.xml
Labels: 기능, UI

#87 [#69] UI 일부 material 테마 적용 및 수정
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ApplyVisitGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/UserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
  app/src/main/res/drawable/button_radius2.xml
  app/src/main/res/layout/fragment_apply_visit_gallery.xml
  app/src/main/res/layout/fragment_author_info.xml
  app/src/main/res/layout/fragment_modify_author_info.xml
  app/src/main/res/layout/fragment_modify_user_info.xml
  app/src/main/res/layout/fragment_user_info.xml
  app/src/main/res/layout/fragment_visit_gallery_history.xml
  app/src/main/res/layout/row_author_review_bottom_sheet.xml
Labels: UI

#95 [#92] 나의 갤러리 관심작품에서 검색 화면으로 이동기능 추가
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/InterestingPieceFragment.kt
Labels: 기능

#96 [#90] 로그인 및 홈화면 이동
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/res/layout/activity_info_all.xml
  app/src/main/res/layout/activity_info_one.xml
  app/src/main/res/layout/activity_update_author.xml
  app/src/main/res/layout/dialog_custom.xml
  app/src/main/res/layout/fragment_guide_line.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_register_author.xml
  app/src/main/res/layout/info_all.xml
Labels: 기능, 리팩토링, UI

#98 [#86] feature 나의 갤러리 화면 이동
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchaseCancelFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/RefundFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalePieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/SalePieceAdapter.kt
  app/src/main/res/layout/row_sale_piece.xml
  app/src/main/res/values/themes.xml
Labels: 기능

#99 [#91] 회원정보 전시실 방문 작가 상세보기 화면 이동
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/ModifyAuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ApplyVisitGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ModifyUserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/UserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
Labels: 기능

#109 [#104] 화면 이동 관련 버그 수정
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyNewFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyPopFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderMainFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/SearchFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/SearchResultFragment.kt
Labels: 버그, 리팩토링

#110 [#106] feature 나의 갤러리 화면 이동 리팩토링
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchaseCancelFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/RefundFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
Labels: 기능, 리팩토링

#111 [#108] fragment 이동 코드 수정
  app/src/main/java/kr/co/lion/unipiece/ui/author/GuideLineFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/RegisterAuthorFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/JoinFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
Labels: 리팩토링

#112 [#105] 프래그먼트 교체 코드 리팩토링 및 툴바 홈버튼 수정
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorReviewBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/ModifyAuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ApplyVisitGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ModifyUserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/UserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
Labels: 리팩토링

#113 #103 feature 화면이동 리팩토링
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/FollowActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/MyPageFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/cart/CartActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/DeliveryAddFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderSuccessFragment.kt
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_order_main.xml
  app/src/main/res/layout/row_follow.xml
Labels: 리팩토링

#115 [#114] homefragment backstack 수정
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoOneActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
Labels: 버그

#118 [#116] 파이어베이스, 뷰모델, 기타 라이브러리 설정
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/unipiece/model/SearchAuthorData.kt
  app/src/main/java/kr/co/lion/unipiece/model/SearchPieceData.kt
  app/src/main/java/kr/co/lion/unipiece/model/SearchResultData.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/SearchResultFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchAuthorViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchPieceViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchResultAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/TitleAuthorViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/TitlePieceViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/util/ImageUtil.kt
  app/src/main/res/layout/activity_buy_detail.xml
  build.gradle.kts
Labels: 기능

#120 [#119] Repository 패키지 생성
  app/src/main/java/kr/co/lion/unipiece/repository/UserInfoRepository.kt
Labels: 기능

#122 [#121] db 패키지 생성
  app/src/main/java/kr/co/lion/unipiece/db/remote/UserInfoDataSource.kt
Labels: 기능

#124 [#123] SquareImageView 패키지 경로 오류
  app/src/main/res/layout/activity_buy_detail.xml
Labels: 버그

#127 [#126] feature 작품 등록 신청 UI 수정
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/res/layout/activity_sales_application.xml
Labels: 기능, UI

#130 [#125] 리사이클러뷰 어댑터 파일 분리 갤러리 방문 신청 UI 수정
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorReviewBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/adapter/AuthorPiecesAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/adapter/AuthorReviewAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/adapter/VisitGalleryAdapter.kt
  app/src/main/res/layout/fragment_apply_visit_gallery.xml
Labels: 리팩토링, UI

#133 [#117] feature 주문하기 뷰 추가 및 리사이클러뷰 어댑터
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/CartAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/cart/CartActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderMainFragment.kt
  app/src/main/res/layout/activity_cart.xml
  app/src/main/res/layout/fragment_order_main.xml
  app/src/main/res/layout/row_cart.xml
  app/src/main/res/layout/row_order_main.xml
Labels: 기능, 리팩토링, UI

#135 [#128] 기본 회원가입 구현
  app/src/main/java/kr/co/lion/unipiece/db/remote/UserInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/UserInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/JoinFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginViewModel.kt
Labels: 기능

#136 [#129] 작품 종류 drawer 수정
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyFragment.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_buy.xml
  app/src/main/res/menu/menu_buy_drawer.xml
Labels: 기능

#139 [#137] 회원가입 입력 검사 및 아이디 중복 검사
  app/src/main/java/kr/co/lion/unipiece/db/remote/UserInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/JoinFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginViewModel.kt
  app/src/main/res/layout/fragment_join.xml
Labels: 기능

#141 [#140] 닉네임 입력 dialog 구현
  app/src/main/java/kr/co/lion/unipiece/ui/login/JoinFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/NicknameDialog.kt
  app/src/main/res/layout/fragment_nickname_dialog.xml
Labels: 기능, UI

#143 [#142] 아이디 중복 검사 viewmodel 사용
  app/src/main/java/kr/co/lion/unipiece/ui/login/JoinFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginViewModel.kt
Labels: 기능

#145 [#144] kakaologin 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/ui/login/JoinFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/NicknameDialog.kt
  app/src/main/res/layout/fragment_nickname_dialog.xml
  settings.gradle.kts
Labels: 기능

#148 [#146] Naverlogin 구현
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
Labels: 기능

#147 [#132] 작가 상세 정보 mvvm 구현 db 연동
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/AuthorInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoViewModel.kt
  app/src/main/res/layout/fragment_author_info.xml
Labels: 기능

#151 [#131] feature 작품 등록 신청
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceAddInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/PieceAddInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceAddInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/PieceAddInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/util/CameraUtil.kt
  app/src/main/res/layout/activity_sales_application.xml
  app/src/main/res/xml/file_path.xml
Labels: 기능

#152 [#138] 작품 전체 모아보기 기능 구현
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/PieceInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyNewFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyPopFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyNewAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyPopAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/util/ImageUtil.kt
  app/src/main/res/layout/item_buy.xml
Labels: 기능

#153 [#150] 갤러리 방문 신청 datepicker 수정
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ApplyVisitGalleryFragment.kt
  app/src/main/res/layout/fragment_apply_visit_gallery.xml
Labels: 기능, UI

#157 [#149] 로그인 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/PreferenceUtil.kt
  app/src/main/java/kr/co/lion/unipiece/UniPieceApplication.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/UserInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginViewModel.kt
  app/src/main/res/layout/fragment_login.xml
Labels: 기능

#159 [#158] 자동 로그인 기능 구현
  app/src/main/java/kr/co/lion/unipiece/PreferenceUtil.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
Labels: 기능

#160 [#156] 세부 카테고리별로 작품 모아보기 기능
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyNewFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyPopFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyNewAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyPopAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/util/ImageUtil.kt
Labels: 기능, UI

#166 [#164] pieceInfo 관련 작업
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyViewModel.kt
Labels: 기능, 리팩토링

#162 [#154] 작가 리뷰 mvvm 구현 db 연동
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorReviewDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/AuthorReviewData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorReviewRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorReviewBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/adapter/AuthorReviewAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorReviewViewModel.kt
  app/src/main/res/layout/fragment_author_info.xml
  app/src/main/res/layout/fragment_author_review_bottom_sheet.xml
  app/src/main/res/layout/row_author_review_bottom_sheet.xml
Labels: 기능

#167 [#165] 로그아웃 기능 구현
  app/src/main/java/kr/co/lion/unipiece/PreferenceUtil.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/MyPageFragment.kt
Labels: 기능

#168 [#163] 작가 정보의 작품 리스트
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorReviewBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/adapter/AuthorPiecesAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
Labels: 기능

#172 [#170] 작가 정보 수정 mvvm 구현 db 연동
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/AuthorInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/ModifyAuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/ModifyAuthorInfoViewModel.kt
  app/src/main/res/layout/fragment_modify_author_info.xml
Labels: 버그, 기능

#174 [#169] 전시홍보 db 연결
  app/src/main/java/kr/co/lion/unipiece/db/remote/PromoteInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/PromoteInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PromoteInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/PromoteFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/PromoteInfoViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_promote.xml
Labels: 기능

#171 [#134] 주문하기 및 팔로우 리사이클러뷰 분리 및 장바구니 mvvm 구현 db연동
  app/src/main/java/kr/co/lion/unipiece/db/remote/CartDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/DeliveryDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/CartData.kt
  app/src/main/java/kr/co/lion/unipiece/model/DeliveryData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/CartRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/DeliveryRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/FollowActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/adapter/FollowAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/CartAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/DeliveryAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/OrderMainAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/cart/CartActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/cart/CartViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/CustomFullDialogListener.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/CustomFullDialogMaker.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/DeliveryActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/DeliveryAddFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/DeliveryManagerFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/delivery/DeliveryViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderMainFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/order/OrderSuccessFragment.kt
  app/src/main/res/layout/dialog_delivery_add.xml
  app/src/main/res/layout/fragment_order_main.xml
  app/src/main/res/layout/row_cart.xml
  app/src/main/res/layout/row_delivery.xml
  app/src/main/res/layout/row_order_main.xml
Labels: 기능, 리팩토링, UI

#177 [#175] 작가 정보 기본 이미지 변경
  app/src/main/java/kr/co/lion/unipiece/ui/author/adapter/AuthorPiecesAdapter.kt
  app/src/main/res/layout/fragment_author_info.xml
  app/src/main/res/layout/fragment_modify_author_info.xml
  app/src/main/res/layout/row_author_pieces.xml
Labels: 리팩토링, UI

#182 [#181] 마이페이지 회원 정보 mvvm 구현 및 db연동
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/UserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/viewmodel/UserInfoViewModel.kt
  app/src/main/res/layout/fragment_user_info.xml
Labels: 기능

#184 [#161] 작품 상세보기 페이지 상단 작업 완료
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorReviewDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorReviewRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyNewFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyPopFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyNewAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyPopAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyDetailViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyDetailViewModelFactory.kt
  app/src/main/res/layout/activity_buy_detail.xml
Labels: 기능, UI

#188 [#185] 전시홍보 ViewPager 클릭 구현
  app/src/main/java/kr/co/lion/unipiece/db/remote/PromoteInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/PromoteInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PromoteInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/PromoteFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/PromoteInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoOneActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/JoinFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/viewModel/LoginViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/util/ImageUtil.kt
Labels: 기능

#189 [#178] 작가 정보 수정 기능 중 이미지 수정
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/ModifyAuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/ModifyAuthorInfoViewModel.kt
  app/src/main/res/layout/fragment_modify_author_info.xml
Labels: 기능

#195 [#191] 행사 viewpager 클릭 구현
  app/src/main/java/kr/co/lion/unipiece/db/remote/NewsInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/NewsInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/model/PromoteInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/NewsInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/NewsFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/NewsInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoOneActivity.kt
  app/src/main/java/kr/co/lion/unipiece/util/ImageUtil.kt
  app/src/main/res/layout/activity_info_one.xml
Labels: 기능

#194 [#176] 작품 등록 신청 및 판매 작품
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceAddInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/PieceAddInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceAddInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalePieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/SalePieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/PieceAddInfoViewModel.kt
  app/src/main/res/layout/activity_sales_application.xml
  app/src/main/res/layout/fragment_interesting_piece.xml
  app/src/main/res/layout/fragment_my_gallery.xml
  app/src/main/res/layout/fragment_purchased_piece.xml
  app/src/main/res/layout/fragment_sale_piece.xml
  app/src/main/res/layout/row_interesting_piece.xml
  app/src/main/res/layout/row_purchased_piece.xml
Labels: 기능, 리팩토링

#198 [#193] 작가 상세 정보 수정
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorReviewBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/adapter/AuthorReviewAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
  app/src/main/res/layout/fragment_author_info.xml
  app/src/main/res/layout/fragment_author_review_bottom_sheet.xml
  app/src/main/res/layout/fragment_modify_author_info.xml
  app/src/main/res/layout/row_author_review_bottom_sheet.xml
Labels: 기능

#200 [#196] 전시홍보 recyclerview db 연결
  app/src/main/java/kr/co/lion/unipiece/db/remote/PromoteInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PromoteInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/viewModel/InfoAllViewModel.kt
  app/src/main/res/layout/activity_info_all.xml
Labels: 기능

#203 [#190] 회원 정보 수정 탈퇴 기능
  app/src/main/java/kr/co/lion/unipiece/db/remote/UserInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/UserInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ModifyUserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/viewmodel/ModifyUserInfoViewModel.kt
  app/src/main/res/layout/fragment_modify_user_info.xml
Labels: 기능

#202 [#201] 소식 recyclerview db 연결
  app/src/main/java/kr/co/lion/unipiece/db/remote/NewsInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/PromoteInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/NewsInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/PromoteInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/viewModel/InfoAllViewModel.kt
Labels: 기능

#199 [#192] 작품 상세보기 하단 작업
  app/src/main/java/kr/co/lion/unipiece/db/remote/CartDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/LikePieceDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/LikePieceData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/CartRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/LikePieceRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyDetailViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyDetailViewModelFactory.kt
  app/src/main/res/drawable/shopcart_icon_on.xml
  app/src/main/res/layout/activity_buy_detail.xml
Labels: 기능

#210 [#207] 전시실 작품 db 연결
  app/src/main/java/kr/co/lion/unipiece/db/remote/GalleryInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/GalleryInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/GalleryInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/GalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/NewsFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/GalleryInfoViewModel.kt
  app/src/main/res/layout/fragment_gallery.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 기능

#213 [#211] 전시실 작품 viewpager 클릭 구현
  app/src/main/java/kr/co/lion/unipiece/db/remote/GalleryInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/GalleryInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/GalleryInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/GalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/GalleryInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoOneActivity.kt
  app/src/main/java/kr/co/lion/unipiece/util/ImageUtil.kt
Labels: 기능

#212 [#209] 구매 부분 코드 수정
  app/src/main/java/kr/co/lion/unipiece/model/CartData.kt
  app/src/main/java/kr/co/lion/unipiece/model/LikePieceData.kt
  app/src/main/java/kr/co/lion/unipiece/model/PieceInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyNewFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyPopFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyNewAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/adapter/BuyPopAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyDetailViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/viewmodel/BuyViewModel.kt
Labels: 리팩토링

#217 [Feature] 작품 랭킹 기능 구현 #215
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/adapter/RankPieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/viewmodel/RankViewModel.kt
  app/src/main/res/layout/fragment_rank.xml
Labels: 기능

#216 [#214] 전시실 작품 recyclerview db연결
  app/src/main/java/kr/co/lion/unipiece/db/remote/GalleryInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/GalleryInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/GalleryInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/NewsInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/viewModel/InfoAllViewModel.kt
Labels: 기능

#221 [#220] 회원 상태 확인하기
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
  app/src/main/res/layout/activity_info_one.xml
  app/src/main/res/layout/fragment_home.xml
Labels: 기능

#219 [#205] 전시실 방문 신청 목록 mvvm 구현 및 db연동 기능
  app/src/main/java/kr/co/lion/unipiece/db/remote/VisitAddDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/VisitAddData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/VisitAddRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/adapter/VisitGalleryAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/viewmodel/VisitGalleryViewModel.kt
  app/src/main/res/layout/fragment_visit_gallery_history.xml
Labels: 기능

#222 [#197] 작품 등록 신청 수정
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceAddInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/PieceAddInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceAddInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/SalePieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/PieceAddInfoViewModel.kt
  app/src/main/res/layout/activity_sales_application.xml
  app/src/main/res/layout/row_sale_piece.xml
Labels: 기능

#226 [#218] 작가 판매횟수 랭킹 화면
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankAuthorFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankSaleFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/adapter/RankAuthorVPAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/adapter/RankSaleAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/viewmodel/RankViewModel.kt
Labels: 기능

#227 [#225] 작가 recyclerview 구현하기
  app/build.gradle.kts
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/AuthorAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoAllAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/util/ImageUtil.kt
  app/src/main/res/layout/author_list.xml
Labels: 기능

#230 [#229] viewmodel 분리하기
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/AuthorAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/GalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/HomeFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/NewsFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/PromoteFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/GalleryInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/HomeViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/NewsInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/home/viewModel/PromoteInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/infomation/InfoOneActivity.kt
Labels: 기능

#231 [#208] feature 배송지 관리 페이지
  app/src/main/java/kr/co/lion/unipiece/db/remote/DeliveryDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/DeliveryRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/FollowActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/adapter/FollowAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/CustomDeleteDialog.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryAddFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryManagerFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryUpdateFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/OrderActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/OrderMainFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/DeliveryAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/viewmodel/DeliveryViewModel.kt
  app/src/main/res/drawable/arrow_forward_ios_icon.xml
  app/src/main/res/drawable/lightgray_radius.xml
  app/src/main/res/layout/row_delivery.xml
  app/src/main/res/layout/row_follow.xml
Labels: 기능, UI

#233 [#232] xml 수정
  app/src/main/res/layout/activity_info_one.xml
  app/src/main/res/layout/fragment_guide_line.xml
Labels: UI

#236 [#224] 관심 작품 목록
  app/src/main/java/kr/co/lion/unipiece/db/remote/LikePieceDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/LikePieceRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/InterestingPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/InterestingPieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/InterestingPieceViewModel.kt
  app/src/main/res/layout/fragment_interesting_piece.xml
Labels: 기능, UI

#239 [#223] 전시실 방문 신청수정 목록 mvvm 구현 및 db연동 기능
  app/src/main/java/kr/co/lion/unipiece/db/remote/VisitAddDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/VisitAddData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/VisitAddRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ApplyVisitGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/adapter/VisitGalleryAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/viewmodel/ApplyVisitGalleryViewModel.kt
  app/src/main/res/layout/fragment_apply_visit_gallery.xml
  app/src/main/res/layout/fragment_visit_gallery_history.xml
  app/src/main/res/layout/row_visit_gallery_history.xml
Labels: 버그, 기능

#243 [#240] 회원 정보 보기 수정
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/UserInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/viewmodel/UserInfoViewModel.kt
Labels: 버그

#242 [#237] 구매한 작품 목록
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceBuyInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/PieceBuyInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceBuyInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/PurchasedPieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/PurchasedPieceViewModel.kt
  app/src/main/res/layout/fragment_purchased_piece.xml
  app/src/main/res/layout/row_purchased_piece.xml
Labels: 기능, UI

#247 [#244] 구매한 작품 상세보기
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceBuyInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceBuyInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/PurchasedPieceDetailViewModel.kt
  app/src/main/res/layout/fragment_purchased_piece_detail.xml
  app/src/main/res/layout/row_interesting_piece.xml
  app/src/main/res/layout/row_purchased_piece.xml
  app/src/main/res/layout/row_sale_piece.xml
Labels: 기능, UI

#250 [#246] layout xml 수정
  app/src/main/java/kr/co/lion/unipiece/ui/author/AuthorReviewBottomSheetFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/ApplyVisitGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/VisitGalleryHistoryFragment.kt
  app/src/main/res/layout/fragment_apply_visit_gallery.xml
  app/src/main/res/layout/fragment_author_info.xml
  app/src/main/res/layout/fragment_modify_author_info.xml
  app/src/main/res/layout/fragment_modify_user_info.xml
Labels: UI

#254 [#245] 검색 기능 추가
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/SearchResultData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/SearchFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/SearchResultFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchAuthorViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchPieceViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/SearchResultAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/TitleAuthorViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/adapter/TitlePieceViewHolder.kt
  app/src/main/java/kr/co/lion/unipiece/ui/search/viewmodel/SearchViewModel.kt
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_result.xml
Labels: 기능

#249 [#235] 작가 정보 등록하기 구현
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorAddDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/AuthorAddData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorAddRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/GuideLineFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/RegisterAuthorFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorAddViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/NicknameDialog.kt
  app/src/main/res/layout/fragment_guide_line.xml
  app/src/main/res/layout/fragment_register_author.xml
Labels: 기능

#253 [#252] 반품 접수
  app/src/main/java/kr/co/lion/unipiece/db/remote/PieceBuyInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/PieceBuyInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/RefundFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/RefundViewModel.kt
  app/src/main/res/layout/fragment_purchase_cancel.xml
  app/src/main/res/layout/fragment_refund.xml
Labels: 기능, UI

#259 [#257] Follow 관련 DB 파일 분리, 마이페이지 수정
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorFollowDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorFollowRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/MyPageFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/viewmodel/MyPageViewModel.kt
  app/src/main/res/layout/fragment_my_page.xml
Labels: 기능, 리팩토링

#262 [#234] feature 팔로우 작가 목록 어답터
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/FollowActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/adapter/FollowAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/viewmodel/FollowViewModel.kt
Labels: 기능

#263 [#255] 작가 랭킹 뒤로가기 오류 수정
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankAuthorFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/rank/RankFragment.kt
Labels: 버그

#260 [#256] 작가 정보 갱신하기 구현
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorAddDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/model/AuthorAddData.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorAddRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/ModifyAuthorInfoFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/RegisterAuthorFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/UpdateAuthorActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/AuthorAddViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/viewmodel/ModifyAuthorInfoViewModel.kt
  app/src/main/res/layout/activity_update_author.xml
  app/src/main/res/layout/fragment_register_author.xml
Labels: 기능

#261 [#238] feature 장바구니, 주문하기, 주소검색API
  app/src/main/AndroidManifest.xml
  app/src/main/java/kr/co/lion/unipiece/db/remote/CartDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/DeliveryDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/CartRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/buy/BuyDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/CartActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/CustomCloseDialog.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryAddFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryUpdateFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/OrderActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/OrderMainFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/SearchAddressActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/CartAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/DeliveryAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/OrderMainAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/viewmodel/CartViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/viewmodel/DeliveryViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/viewmodel/OrderViewModel.kt
  app/src/main/res/layout/activity_search_address.xml
  app/src/main/res/layout/fragment_delivery_add.xml
  app/src/main/res/layout/fragment_delivery_update.xml
  app/src/main/res/layout/fragment_order_main.xml
  app/src/main/res/layout/row_cart.xml
  app/src/main/res/layout/row_order_main.xml
Labels: 기능, UI

#265 [#258] 나의 갤러리 수정 및 보완
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorAddDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorAddRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/InterestingPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchaseCancelFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceDetailFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/PurchasedPieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/RefundFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalePieceFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/SalesApplicationActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/InterestingPieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/MyGalleryViewPagerAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/PurchasedPieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/adapter/SalePieceAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/InterestingPieceViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/PieceAddInfoViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/PurchasedPieceDetailViewModel.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/viewmodel/RefundViewModel.kt
  app/src/main/res/layout/fragment_sale_piece.xml
  app/src/main/res/layout/row_interesting_piece.xml
  app/src/main/res/layout/row_purchased_piece.xml
  app/src/main/res/layout/row_sale_piece.xml
Labels: 버그, 기능, UI

#267 [#266]장바구니 선택삭제 전체삭제 기능
  app/src/main/java/kr/co/lion/unipiece/model/CartInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/model/PieceInfoData.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/CartActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryAddFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryManagerFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/OrderActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/OrderMainFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/adapter/CartAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/viewmodel/CartViewModel.kt
  app/src/main/res/layout/activity_cart.xml
Labels: 기능

#268 [Feat]#264 장바구니 체크박스, 팔로우목록 DB연동, 클릭이벤트
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorFollowDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/db/remote/AuthorInfoDataSource.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorFollowRepository.kt
  app/src/main/java/kr/co/lion/unipiece/repository/AuthorInfoRepository.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/FollowActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/adapter/FollowAdapter.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mypage/viewmodel/FollowViewModel.kt
  app/src/main/res/layout/row_follow.xml
Labels: 기능, UI

#271 [#269] 앱 로고 적용하기
  app/src/main/AndroidManifest.xml
  app/src/main/ic_main_logo-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_main_logo.xml
  app/src/main/res/mipmap-anydpi-v26/ic_main_logo_round.xml
  app/src/main/res/mipmap-hdpi/ic_main_logo.webp
  app/src/main/res/mipmap-hdpi/ic_main_logo_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_main_logo_round.webp
  app/src/main/res/mipmap-mdpi/ic_main_logo.webp
  app/src/main/res/mipmap-mdpi/ic_main_logo_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_main_logo_round.webp
  app/src/main/res/mipmap-xhdpi/ic_main_logo.webp
  app/src/main/res/mipmap-xhdpi/ic_main_logo_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_main_logo_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_logo.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_logo_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_main_logo_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_logo.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_logo_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_main_logo_round.webp
  app/src/main/res/values/ic_main_logo_background.xml
Labels: 기능, UI

#272 [Feat]#264 배송메모, 배송지관리에서 주문하기 넘어갈때 데이터이슈 해결
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryAddFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryManagerFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/DeliveryUpdateFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/OrderMainFragment.kt
  app/src/main/res/layout/fragment_delivery_add.xml
  app/src/main/res/layout/fragment_delivery_update.xml
Labels: 기능, UI

#274 [#273] 시연 전 자잘한 오류 수정 및 기능 추가
  app/src/main/java/kr/co/lion/unipiece/ui/MainActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/GuideLineFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/author/RegisterAuthorFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/login/LoginFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/mygallery/MyGalleryFragment.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/CartActivity.kt
  app/src/main/java/kr/co/lion/unipiece/ui/payment/OrderSuccessFragment.kt
  app/src/main/res/layout/fragment_order_success.xml
Labels: 버그, 기능, 리팩토링, UI
